name: On Push
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install --include=dev
      - name: Run Tests
        run: npm test
  release:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install --include=dev
      - name: Build
        run: npm run build:release
      - name: Package
        run: npm run package
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build.zip
