name: On Push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install --include=dev
      - name: Run Tests
        run: npm test
      - name: Build
        id: build
        if: startsWith(github.ref, 'refs/tags/')
        run: npm run build:release
      - name: Package
        id: package
        if: steps.build.outcome != 'skipped'
        run: npm run package
      - name: Release
        if: steps.package.outcome != 'skipped'
        uses: softprops/action-gh-release@v1
        with:
          files: build.zip
